sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - docker build -t nakul/docker-react -f Dockerfile.dev .

script:
  - docker run nakul/docker-react npm test -- --coverage
  - travis_wait

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: nakul-docker-react
  env: NakulDockerReact-env
