sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  - docker build -t nakul/awsproject:latest -f Dockerfile.dev .

script:
  #- docker run nakul/awsproject npm run test -- --coverage
  - npm install
  - npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAI367IOYXH6OUHRKQ"
  secret_access_key: "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"
  region: "us-east-2"
  app: "nakul-docker-react"
  env: "NakulDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-135015496169"
  bucket_path: "nakul-docker-react"
  on:
    branch: master
