sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

before_install:
  - docker build -t nakul/docker-react -f Dockerfile.dev .

script:
  - docker run nakul/docker-react npm test -- --coverage
  - travis_wait 1

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "nakul-docker-react"
  env: "NakulDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-135015496169"
  bucket_path: "nakul-docker-react"
  on:
    branch: master
