sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - docker build -t nakul/docker-react -f Dockerfile.dev .

script:
  - docker run nakul/docker-react npm run test -- --coverage
